"""YOLO Pose person detection for the elderly-monitor pipeline.

This module reads the timestamped frames generated by frame_sampler.py,
runs a pretrained Ultralytics YOLO pose model, and saves:
    - annotated images
    - one JSON observation per frame
    - a combined pose_manifest.json

The current implementation assumes one main person in the scene and selects
the highest-confidence person detection for downstream state analysis.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ultralytics import YOLO


# COCO keypoint order used by the YOLO pose models.
KEYPOINT_NAMES = [
    "nose",
    "left_eye",
    "right_eye",
    "left_ear",
    "right_ear",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
]


class PoseDetector:
    """Run YOLO pose inference on individual images."""

    def __init__(
        self,
        model_name: str = "yolo11n-pose.pt",
        confidence: float = 0.35,
        image_size: int = 640,
        device: str | None = "cpu",
    ) -> None:
        if not 0.0 < confidence < 1.0:
            raise ValueError("confidence must be between 0 and 1")

        if image_size <= 0:
            raise ValueError("image_size must be greater than 0")

        self.model_name = model_name
        self.confidence = confidence
        self.image_size = image_size
        self.device = device

        print(f"Loading YOLO pose model: {model_name}")
        self.model = YOLO(model_name)

    def detect(
        self,
        image_path: Path,
        timestamp_sec: float,
        sample_number: int,
    ) -> tuple[dict[str, Any], Any]:
        """Run pose detection on one image.

        Returns:
            observation: JSON-serializable detection information.
            annotated_image: NumPy image returned by YOLO plotting.
        """
        image_path = Path(image_path)

        if not image_path.is_file():
            raise FileNotFoundError(f"Image not found: {image_path}")

        results = self.model.predict(
            source=str(image_path),
            conf=self.confidence,
            imgsz=self.image_size,
            device=self.device,
            verbose=False,
        )

        if not results:
            return self._empty_observation(
                image_path=image_path,
                timestamp_sec=timestamp_sec,
                sample_number=sample_number,
            ), None

        result = results[0]

        # YOLO's result.plot() gives us an annotated image containing
        # bounding boxes and pose keypoints.
        annotated_image = result.plot(
            boxes=True,
            labels=True,
            kpt_line=True,
        )

        if result.boxes is None or len(result.boxes) == 0:
            return self._empty_observation(
                image_path=image_path,
                timestamp_sec=timestamp_sec,
                sample_number=sample_number,
            ), annotated_image

        # A pose model may theoretically contain multiple detections.
        # For this assignment, choose the highest-confidence person.
        classes = result.boxes.cls.cpu().numpy()
        box_confidences = result.boxes.conf.cpu().numpy()

        person_indices = [
            index
            for index, class_id in enumerate(classes)
            if int(class_id) == 0  # COCO class 0 = person
        ]

        if not person_indices:
            return self._empty_observation(
                image_path=image_path,
                timestamp_sec=timestamp_sec,
                sample_number=sample_number,
            ), annotated_image

        best_index = max(
            person_indices,
            key=lambda index: float(box_confidences[index]),
        )

        bbox = result.boxes.xyxy[best_index].cpu().numpy().tolist()
        person_confidence = float(box_confidences[best_index])

        keypoints_dict = self._extract_keypoints(result, best_index)

        observation = {
            "sample_number": sample_number,
            "timestamp_sec": round(float(timestamp_sec), 3),
            "image": image_path.name,
            "person_detected": True,
            "person_confidence": round(person_confidence, 4),
            "bbox_xyxy": [
                round(float(value), 2)
                for value in bbox
            ],
            "keypoints": keypoints_dict,
        }

        return observation, annotated_image

    @staticmethod
    def _extract_keypoints(
        result: Any,
        person_index: int,
    ) -> dict[str, dict[str, float | None]]:
        """Convert YOLO keypoints into readable JSON."""

        if result.keypoints is None:
            return {
                name: {"x": None, "y": None, "confidence": None}
                for name in KEYPOINT_NAMES
            }

        data = result.keypoints.data[person_index].cpu().numpy()

        output: dict[str, dict[str, float | None]] = {}

        for index, name in enumerate(KEYPOINT_NAMES):
            if index >= len(data):
                output[name] = {
                    "x": None,
                    "y": None,
                    "confidence": None,
                }
                continue

            point = data[index]

            x = float(point[0])
            y = float(point[1])

            confidence = (
                float(point[2])
                if len(point) >= 3
                else None
            )

            output[name] = {
                "x": round(x, 2),
                "y": round(y, 2),
                "confidence": (
                    round(confidence, 4)
                    if confidence is not None
                    else None
                ),
            }

        return output

    @staticmethod
    def _empty_observation(
        image_path: Path,
        timestamp_sec: float,
        sample_number: int,
    ) -> dict[str, Any]:
        """Return a standard observation when nobody is detected."""

        return {
            "sample_number": sample_number,
            "timestamp_sec": round(float(timestamp_sec), 3),
            "image": image_path.name,
            "person_detected": False,
            "person_confidence": None,
            "bbox_xyxy": None,
            "keypoints": {
                name: {
                    "x": None,
                    "y": None,
                    "confidence": None,
                }
                for name in KEYPOINT_NAMES
            },
        }


def run_pose_pipeline(
    manifest_path: Path,
    output_dir: Path,
    model_name: str = "yolo11n-pose.pt",
    confidence: float = 0.35,
    image_size: int = 640,
    device: str | None = "cpu",
) -> dict[str, Any]:
    """Run YOLO pose on all frames listed in frame_manifest.json."""

    manifest_path = Path(manifest_path)
    output_dir = Path(output_dir)

    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"Frame manifest not found: {manifest_path}"
        )

    with manifest_path.open("r", encoding="utf-8") as file:
        manifest = json.load(file)

    frames = manifest.get("frames")

    if not isinstance(frames, list) or not frames:
        raise ValueError(
            "frame_manifest.json does not contain any sampled frames."
        )

    observations_dir = output_dir / "observations"
    annotated_dir = output_dir / "annotated"

    observations_dir.mkdir(parents=True, exist_ok=True)
    annotated_dir.mkdir(parents=True, exist_ok=True)

    # Remove old generated outputs.
    for old_file in observations_dir.glob("pose_*.json"):
        old_file.unlink()

    for old_file in annotated_dir.glob("pose_*.jpg"):
        old_file.unlink()

    detector = PoseDetector(
        model_name=model_name,
        confidence=confidence,
        image_size=image_size,
        device=device,
    )

    observations: list[dict[str, Any]] = []

    manifest_root = manifest_path.parent

    for frame_info in frames:
        sample_number = int(frame_info["sample_number"])
        timestamp_sec = float(frame_info["timestamp_sec"])

        frame_relative_path = frame_info["file"]

        # frame_info["file"] is normally "frames/frame_....jpg"
        image_path = manifest_root / frame_relative_path

        observation, annotated_image = detector.detect(
            image_path=image_path,
            timestamp_sec=timestamp_sec,
            sample_number=sample_number,
        )

        observations.append(observation)

        observation_path = (
            observations_dir
            / f"pose_{sample_number:06d}.json"
        )

        with observation_path.open("w", encoding="utf-8") as file:
            json.dump(
                observation,
                file,
                indent=2,
                ensure_ascii=False,
            )
            file.write("\n")

        if annotated_image is not None:
            import cv2

            annotated_path = (
                annotated_dir
                / f"pose_{sample_number:06d}.jpg"
            )

            written = cv2.imwrite(
                str(annotated_path),
                annotated_image,
            )

            if not written:
                raise OSError(
                    f"Could not write annotated frame: {annotated_path}"
                )

        print(
            f"[{sample_number:03d}/{len(frames):03d}] "
            f"{timestamp_sec:6.2f}s "
            f"person={observation['person_detected']} "
            f"confidence={observation['person_confidence']}"
        )

    combined = {
        "source_manifest": str(manifest_path.resolve()),
        "model": model_name,
        "confidence_threshold": confidence,
        "image_size": image_size,
        "device": device,
        "frame_count": len(observations),
        "person_detected_count": sum(
            1
            for item in observations
            if item["person_detected"]
        ),
        "observations": observations,
    }

    combined_path = output_dir / "pose_manifest.json"

    with combined_path.open("w", encoding="utf-8") as file:
        json.dump(
            combined,
            file,
            indent=2,
            ensure_ascii=False,
        )
        file.write("\n")

    return combined